import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import { Header } from "@/components/shared";
import "./globals.css";
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
})



export const metadata: Metadata = {
  title: "Next Pizza | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        <main className="min-h-screen">
        <Header/>
       {children}
      </main>
 
      </body>
    </html>
  );
}
